print("You will give me five numbers and then I will give you your average.")

number1 = input("give me one number between 1-10:")
number2 = input("give me one number between 1-10:")
number3 = input("give me one number between 1-10:")
number4 = input("give me one number between 1-10:")
number5 = input("give me one number between 1-10:")
number1 = int(number1)
number2 = int(number2)
number3 = int(number3)
number4 = int(number4)
number5 = int(number5)
print(number1 + number2 + number3 + number4 + number5)
average = (number1 + number2 + number3 + number4 + number5 / 5)
print("your average is:")
print(average)
